### ISSUE TITLE
MeetUp Schedule

### ISSUE THREAD

**Issue by michaeltlombardi** [stlpsug/stlpsug#11]
For last month, this month, and next month we've been meeting on the third Thursday of every month.

Unless there are good reasons not to, I propose we make the calendar for the rest of 2016 as follows:

| Month | Date |
| :-- | :-: |
| April | 21 |
| May | 19 |
| June | 16 |
| July | 21 |
| August | 18 |
| September | 15 |
| October | 20 |
| November | 17 |
| December | 15 |

**Comment by jamiemoyer** [comment]
Concur

**Comment by michaeltlombardi** [comment]
Since no one else has chimed in on this, closing for now. If anyone has concerns or problems with this schedule, please reopen the issue.
