### ISSUE TITLE
Suggested Topic List

### ISSUE THREAD

**Issue by MikeShepard** [stlpsug/stlpsug#12]
Would be cool to have a place for people to suggest topics.  Perhaps keep a running list and a way for people to volunteer for them?

Some more topics I thought of:
- Parameter Validation attributes
- Supporting WhatIf and Confirm (correctly)
- Using diffferent kinds of output (Write-Output, Write-Debug, Write-Verbose, etc.)
- Differences in using Foreach (keyword) and Foreach-Object (cmdlet)

**Comment by michaeltlombardi** [comment]
I definitely think this is a good idea for a continually-updated document in the repository - maybe once a topic is covered at a MeetUp we include a link to the presentation notes?

I think removing a topic from the list once it's covered might result in people re-requesting that topic.

**Comment by MikeShepard** [comment]
I like it.

On Fri, Mar 18, 2016 at 12:54 PM, Michael T Lombardi <
notifications@github.com> wrote:

> I definitely think this is a good idea for a continually-updated document
> in the repository - maybe once a topic is covered at a MeetUp we include a
> link to the presentation notes?
> 
> I think removing a topic from the list once it's covered might result in
> people re-requesting that topic.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/stlpsug/stlpsug/issues/12#issuecomment-198470335

## 

https://powershellstation.com

**Comment by michaeltlombardi** [comment]
I'm going to update #1 (Directory Structure) to include these changes and close this out.
