### ISSUE TITLE
May Meetup Topic/Presenter

### ISSUE THREAD

**Issue by doesitscript** [stlpsug/stlpsug#13]
Michael Green has offered to present at the May Meetup on either continuous integration or Pester. I prefer pester  :) but the non-core PS community who we are trying to target would probably gravitate more towards continuous integration. Thoughts? What do you say?

**Comment by michaeltlombardi** [comment]
Can you do CI without first writing unit-tests? 

I understand that it's probably easier conceptually to move towards CI, but I think that might be an anti-pattern we shouldn't encourage. @mgreenegit, other folks who are looking to do CI, what are your thoughts? Do you think it makes sense to learn and integrate unit tests first or am I overstating the potential concerns?

**Comment by michaeltlombardi** [comment]
Micah Battin presented on PowerShell Functions.
