### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by doesitscript** [stlpsug/stlpsug#14]
We need a 124 X 124 icon to promote on the AMS 2016 page.  I think Mike and I could tackle this this weekend.  I'm planning on posting this here for feedback. If you are artistic, feel free to take this on.  I'm working on one that has the arch in the background otherwise.

**Comment by michaeltlombardi** [comment]
The background should be [PowerShell Blue](http://www.leeholmes.com/blog/2008/06/01/powershells-noble-blue/) for obvious reasons, I think.  Maybe something like `∩ >_` in white on the PowerShell Blue background? 

If anyone can find a character that looks close enough to the arch, I think keeping the symbol simple and evocative of the PowerShell prompt is a good idea. The intersection symbol above might work okay if the font size for it is increased to make it taller than the right-caret.

**Comment by michaeltlombardi** [comment]
See [here](https://github.com/doesitscript/stlpsug/blob/master/documents/media/icons/Arch_NoLayers_Centered.png?raw=true) for the icon  @doesitscript has made up for us.

@stlpsug/didacts : any comments or concerns?

**Comment by MikeShepard** [comment]
Looks awesome to me,

**Comment by ThePowershellNinja** [comment]
Love it

-----Original Message-----

**Comment by michaeltlombardi** [comment]
Good enough for me. This issue is closed by @doesitscript's PR in #15
