### ISSUE TITLE
May Meetup Logistics

### ISSUE THREAD

**Issue by doesitscript** [stlpsug/stlpsug#16]
- Would suggest recording Michael Greene's presentation/streaming this.
  Dry run would  probably be advisable. 
  - Location selection.
    Microsoft location ok?

**Comment by michaeltlombardi** [comment]
I think we really do need to nail down a story for recording and sharing presentations afterward. It's allows members who couldn't make it to still see the presentations, shares the work of the speakers, and allows people to go back and reference those talks again if they think they've forgotten something.

**Comment by michaeltlombardi** [comment]
SLU was kind enough to host us for the evening at @jasonrutherford2014's request.
