### ISSUE TITLE
Get feedback on  on gitter chat integration

### ISSUE THREAD

**Issue by doesitscript** [stlpsug/stlpsug#17]
See example on:
https://github.com/pcgeek86/PSGitHub

**Comment by michaeltlombardi** [comment]
Do we prefer gitter or slack or some other (similar) service for this function? 
**Note:** Any conversations in gitter/slack do exclude more people than directly posting in Github issues (though less than personal email discussion or PMs do).

**Comment by doesitscript** [comment]
Well I like waffle because it seems seemlessly integrated into our github workflow. Let's use that same mentality to make the decision on this one.

**Comment by michaeltlombardi** [comment]
In that case, prefer Gitter over Slack - but we should note in the communication guidelines (#7) what things should go in issues and what should be in Gitter. 

We want to make sure that we maintain as much transparency and availability of information and decision making to everyone as possible.

**Comment by michaeltlombardi** [comment]
Added Gitter integration, waiting for fix to PR (#18) so that badge will be on the same line as the Waffle badge.

You can see the chatroom [here](https://gitter.im/stlpsug/stlpsug)

**Comment by doesitscript** [comment]
I'd consider this closed :)

**Comment by michaeltlombardi** [comment]
Closing then, per completion in #18.
