### ISSUE TITLE
Need April Agenda

### ISSUE THREAD

**Issue by michaeltlombardi** [stlpsug/stlpsug#20]
We require an agenda for April - a speaker, a topic, a plan, etc.

**Comment by doesitscript** [comment]
Agreed Mike. THinking we should put out a Bio with tentative plans for the location.

**Comment by michaeltlombardi** [comment]
We should probably nail down a bio per #23.

**Comment by doesitscript** [comment]
Micah is unable to present. Need a new presenter.

**Comment by michaeltlombardi** [comment]
We've agreed on doing the whiteboard session, correct? Instead of a specific presenter, we'll be at the board discussing topics and let any available SME take the lead for a given topic.

1700-1815: General discussion, introductions.
1815-2015: White Board Session
2015-2030: Organizational Announcements
2030-?: Additional discussions and organizational business (this repository, waffle, gitter, etc).

**Comment by michaeltlombardi** [comment]
Past usefulness.
