### ISSUE TITLE
Need to Choose Static Website Generator

### ISSUE THREAD

**Issue by michaeltlombardi** [stlpsug/stlpsug#6]
The cheapest, simplest, and most transparent way to maintain a website for this organization appears to be a static site generator.
### Benefits
- This allows us to keep drafts, site organization, etc in version control.
- The cost of hosting a static site is free to negligible and can be done via Github, Amazon S3, or Azure.
- A static website using a common repository allows us to use the permissions setup in Github; that is, it requires no additional special considerations.
- The site is not dependent on any one location; both the source documents/configuration and the site itself can be moved away from github or our hosting platform at any time.
### Options
- [Jekyll](https://jekyllrb.com/)
- [Hugo](https://gohugo.io/)
- [PowerSite](https://github.com/Jaykul/PowerSite)

Jekyll is probably the most popular and well documented/supported option.
Hugo is hands-down the most portable option and has a good community.
PowerSite is entirely managed via PowerShell which makes it an attractive option.

My personal preference is to use Hugo and add a repository for a PowerShell wrapper for the executable as an example project for the PSUG. 

I'm open to all options, including those not listed.

**Comment by doesitscript** [comment]
Doesn't github post pages?

**Comment by michaeltlombardi** [comment]
It does, and I suggest we host them either there or in Azure Web sites (for basically free, since we're going static).

But in order to host in either place, you need to generate the static content and upload it.  Hugo, Jekyll, PowerSite, OctoPress, MetalSmith, Hyde, MkDocs - there's _tons_ of static site generators now. We're supersaturated with options.

I'm leaning towards either Hugo (and the PSUG project around writing a module for it) or PowerSite. PowerSite has the advantage of being all .NET and already having PowerShell integration. Hugo is cross platform and self contained, allowing members/people to contribute from any platform and I personally like the configuration.

Or we could set up a CI pipeline for the website using whichever static site generator we choose (I like this idea as well) - but you still need to choose a generator to target.

**Edit:** [This](http://blog.codingoutloud.com/2014/02/14/stupid-azure-trick-5-got-a-penny-run-a-simple-web-app-run-100-on-blob-storage/) is an example of cheap hosting in Azure.

**Comment by doesitscript** [comment]
I like what I see. Writng powershell around hugo might not be something everyone jumps on quickly, I'm thinking that PowerSite may have a wider entry point (easier to start). My two cents... I defer to your judgment.

**Comment by michaeltlombardi** [comment]
I'm not anti PowerSite, it just makes it difficult for me (the ultra minority) to contribute to directly from my laptop for now.

It looks like a good option. I've been kicking the can on Hugo and MkDocs (I think minor tweaking to the [Cerulean](https://bootswatch.com/cerulean/) theme is perfect for us) both, but I've not touched Jekyll/Hyde/PowerSite.

I'm curious to see what other members think (and maybe for an example made in PowerSite).

**Comment by michaeltlombardi** [comment]
With lack of input, for now I'm going to go with [MkDocs](http://www.mkdocs.org/) since it is cross platform and I'm already familiar with it. Plus, it lets us write everything in markdown and convert easily to a website.
