### ISSUE TITLE
Require Communication/Collaboration Guidelines

### ISSUE THREAD

**Issue by michaeltlombardi** [stlpsug/stlpsug#7]
We need to enumerate some sort of way to keep members in contact and provide avenues for members to submit problems, ask questions, etc - making members aware of multiple options seems like it will probably increase the participation.

We might want to model something on a less-formalized version of Ride's [Collaboration Guidelines](https://github.com/ride/collaboration-guides) - it includes details for communication channels and how to escalate when there's a problem, etc.

**Comment by doesitscript** [comment]
Let's start by making what we have available at the next PSUG meeting.

**Comment by michaeltlombardi** [comment]
By making this repository (and all the work in progress) public next Thursday, do you mean? If not, can you clarify?

**Comment by doesitscript** [comment]
Let's post this at the beginning of a slide. My presentation is going to be packed. Perhaps in the closing remarks, or the dotnet object?

**Comment by michaeltlombardi** [comment]
I think it would fit well in the closing remarks and end-of-night links, maybe as a discussion point to get everyone in the room involved after all is said and done?
