### ISSUE TITLE
April Meetup Date

### ISSUE THREAD

**Issue by michaeltlombardi** [stlpsug/stlpsug#9]
Need to decide on an April meetup date -tentatively considering Thursday, April 21 - waiting to hear back from the Mid-Missouri PSUG to ensure we don't conflict.

**Comment by michaeltlombardi** [comment]
Talked with the MidMo PSUG - they're looking at meeting in the first week of April so our tentative date is good to go! Putting it on the schedule.

**Edit:** Actually, I can't push out the MeetUp until we have a location. @jamiemoyer, @doesitscript - did we have any movement on the event being hosted at not-Microsoft next month? Or do you think we'll be able to get the room again?

**Comment by doesitscript** [comment]
Does the Microsoft location work? No volunteers yet.

**Comment by jamiemoyer** [comment]
Awaiting confirmation on availability.

-Jamie

**Comment by jamiemoyer** [comment]
Update: Confirmed / Reserved 

21 April
5-9 PM

-Jamie

**Comment by michaeltlombardi** [comment]
Excellent, do we want to do something more specific for the blurb than last month?

**Comment by michaeltlombardi** [comment]
Finally scheduled the [meetup](http://www.meetup.com/STLPSUG/events/bgrbslyvgbcc/) with a generic placeholder message.
